version: '3'

services:
  db:
    image: "postgres:14-alpine"
    container_name: postgresql
    env_file:
      - ./backend/.env
  web:
    build: ./backend/
    container_name: drf_application
    command: bash entrypoint.sh
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 8080:8000
    env_file:
      - ./backend/.env
    depends_on:
      - db
  nginx:
    image: nginx
    container_name: nginx
    ports:
     - "1180:80"
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=80
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/:/usr/src/frontend/
    depends_on:
      - web
