version: '3.7'

services:
  db:
    image: "postgres:14-alpine"
    container_name: postgresql
    env_file:
      - ./backend/.env
  web:
    build: ./backend/
    container_name: drf_application
    command: bash entrypoint.sh
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
